# -*- coding: utf-8 -*-
"""week10_ex_ksattar_cis502.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCrspMaOyOA0WkYdrbDzzQEDtnU0STL9
"""

#Week 10 Exercise
#Author: Kian Sattar
#Course: CIS 502
#CRN: 47621

#Create and initialize baseline list with required student names contents
students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']

#Create new list containing names from first list that meet certain criteria (length greater than 5)
#Using lambda and filter() functions
selected_students = list(filter(lambda x: (len(x) > 5), students))

#Print filtered list
print(selected_students)