# -*- coding: utf-8 -*-
"""week6-1_ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Di8yRV5kcH4VWxlENatm2Aw9y9K4Vw3V
"""

class CapitalizeIterator():
    def __init__(self, word_list):
        self.word_list = [x.upper() for x in word_list]
        self.index = 0

    def __iter__(self):
        return self

    def __next__(self):
        try:
            result = self.word_list[self.index]
        except IndexError:
            raise StopIteration
        self.index += 1
        return result

word_list = ["python", "is", "awesome"]

iterator = CapitalizeIterator(word_list)

print("Capitalized Words:")

for word in iterator:
  print(word)