# -*- coding: utf-8 -*-
"""week6-1_ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Di8yRV5kcH4VWxlENatm2Aw9y9K4Vw3V
"""
#Iterator class
class CapitalizeIterator():
    def __init__(self, word_list):
        self.word_list = [x.upper() for x in word_list]
        self.index = 0
        
#iter function that returns an iterator object
    def __iter__(self):
        return self
        
#function that returns next possible object of an iteration
#if there are no more possible objects in the iteration, iteration is stopped
    def __next__(self):
        try:
            result = self.word_list[self.index]
        except IndexError:
            raise StopIteration
        self.index += 1
        return result
        
#create a list to iterate through
word_list = ["python", "is", "awesome"]

#call CapitalizeIterator class constructor and instantiate an iterator objec
#pass list as parameter to iterator
iterator = CapitalizeIterator(word_list)

#print title statement
print("Capitalized Words:")

#iterate through list and capitalize all words
#print capitalized words to screen
for word in iterator:
  print(word)