# -*- coding: utf-8 -*-
"""week7_1_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZD0_z8VXUVxyq6mhQ1ZYJAgtrQnYcRZQ
"""

class GradeDescriptor:
    def __init__(self, min_grade, max_grade):
        """
        Constructor method that initializes the minimum and maximum acceptable grades.

        Args:
            min_grade (int): Minimum acceptable grade.
            max_grade (int): Maximum acceptable grade.
        """
        self.min_grade = min_grade
        self.max_grade = max_grade

    def __get__(self, instance, owner):
        """
        Method to retrieve the grade for a particular student.

        Args:
            instance: The instance of the Student class.
            owner: The class that owns this descriptor (Student class).

        Returns:
            int: The grade for the student.
        """
        return instance._grade

    def __set__(self, instance, value):
        """
        Method to set the grade for a particular student.

        Args:
            instance: The instance of the Student class.
            value (int): The grade to set.

        Raises:
            ValueError: If the grade is outside the acceptable range.
        """
        if not (self.min_grade <= value <= self.max_grade):
            raise ValueError(f"Grade must be between {self.min_grade} and {self.max_grade}")
        instance._grade = value

    def __delete__(self, instance):
        """
        Method to delete the grade for a particular student.

        Args:
            instance: The instance of the Student class.
        """
        del instance._grade

class Student:
    def __init__(self, name):
        """
        Constructor method for creating a Student instance.

        Args:
            name (str): Name of the student.
        """
        self.name = name
        self.grade = GradeDescriptor(min_grade=0, max_grade=100)

    def display_grade(self):
        """
        Display the grade of the student.
        """
        print(f"{self.name}'s grade: {self.grade}")

# Example usage
student1 = Student("Alice")
student1.grade = 85  # Set Alice's grade
student1.display_grade()  # Display Alice's grade

student2 = Student("Bob")
student2.grade = 92  # Set Bob's grade
student2.display_grade()  # Display Bob's grade

# Deleting Bob's grade
del student2.grade
print(f"Bob's grade after deletion: {getattr(student2, 'grade', 'N/A')}")

