# -*- coding: utf-8 -*-
"""Week 2_Exercise 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NlxMMy2ZlU91gRFLMdgw6wuRmcXaqQ90
"""

class Rectangle:
  def __init__(self, l, w):
    self.length = l
    self.width = w

  def calc_area(self):
    return (self.length * self.width)

rectangle1 = Rectangle(4, 5)
rectangle2 = Rectangle(5, 6)

print("Rectangle 1 Area: " + str(rectangle1.calc_area()))
print("Rectangle 2 Area: " + str(rectangle2.calc_area()))
