# -*- coding: utf-8 -*-
"""week5_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9VDevu5JhYfD2jtMQzSJrqLpVTdkcjt
"""

# Define Student class
class Student():
    # init function that uses **kwargs to accept unlimited keyworded arguments
    def __init__(self, **kwargs):
        # attributes
        # Uses .get() method to check if the key exists before accessing it.
        # If attribute does not exist, returns 'Unknown'
        self.name = kwargs.get('n', 'Unknown')
        self.age = kwargs.get('a', 'Unknown')
        self.grade = kwargs.get('g', 'Unknown')



# Create objects of Student class
student1 = Student(n='Alice', a='18', g='A')
student2 = Student(n='Bob', a='17')

# Print the name, age, and grade of the students
print(student1.name, student1.age, student1.grade)
print(student2.name, student2.age, student2.grade)