# -*- coding: utf-8 -*-
"""week6-1_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOa0pp-PEP91DV4D_teJ4deJFHWAqSfh
"""

def fibonacci_generator(limit):
  n1, n2 = 0, 1

  while n1 < limit:
    yield n1
    n1, n2 = n2, n1 + n2

limit = 50

fib_sequence = fibonacci_generator(limit)

print("Fibonnaci numbers up to", limit, ":")

for num in fib_sequence:
  print(num, end=" ")