# -*- coding: utf-8 -*-
"""week5_2_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqjvpCpWjv9h5SRjEd9VIFmDLhFO53Ek
"""

#function decorator that converts the return value of a function to uppercase
def uppercase(func):
  def wrapper(*args, **kwargs):
    result = func(*args, **kwargs)
    return result.upper()
  return wrapper

#function that decorator is applied to
@uppercase
def greet(name):
  return f"Hello there {name}!"

#print example output to screen
print(greet("Jimmy"))
print(greet("Jane"))